### ISSUE TITLE
БД

### ISSUE THREAD

**Issue by Fursanov** [pinneer19/todo_app#1]
Добавь в проект sql файлик с кодом твоей базы данных(таблицы, констрейнты, связи, перечисления, индексы, методы и функции если таковые имеются). По ходу дела при появлении новых сущностей будешь обновлять и файл бд.

**Comment by pinneer19** [comment]
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
Такого достаточно или еще нужны запросы к бд?
