### ISSUE TITLE
описание ошибок

### ISSUE THREAD

**Issue by Fursanov** [pinneer19/todo_app#7]
![image](https://github.com/user-attachments/assets/6918927d-3775-4b25-b55c-ad31148bbea7)

хотелось бы видеть описание ошибок не только в консоли но и на самой странице. Как рядовому пользователю понять в чем именно проблема.

**Comment by Fursanov** [comment]
![Снимок экрана от 2024-12-02 16-21-11](https://github.com/user-attachments/assets/49245e29-e85d-4267-97f1-4969014f11f2)

Описание ошибок я видел, но не везде, например вот здесь

**Comment by pinneer19** [comment]
![image](https://github.com/user-attachments/assets/16142355-e210-4382-af4e-9421d1af1239)

**Comment by Fursanov** [comment]
хммммм, ладно, сейчас
